### ISSUE TITLE
Proposal: an easy-to-use pipeline package just for PK/PD

### ISSUE THREAD

**Issue by wlandau** [nlmixrdevelopment/nlmixrtargets#1]
Folks like @billdenney have used `nlmixr` successfully with [`drake`](https://github.com/wlandau/drake), so I would like to chime in about how `nlmixr` could potentially partner with [`drake`](https://github.com/wlandau/drake)'s long-term successor, [`targets`](https://github.com/wlandau/targets).

Unlike [`drake`](https://github.com/wlandau/drake), [`targets`](https://github.com/wlandau/targets) makes it super straightforward to build extensions for specialized use cases. For example, I recently created a new R package called [`stantargets`](https://github.com/wlandau/stantargets), which combines [`targets`](https://github.com/wlandau/targets) with [`cmdstanr`](https://github.com/stan-dev/cmdstanr) to make it easy to write large Bayesian data analysis pipelines. Complicated workflows like [this one](https://github.com/wlandau/targets-stan/blob/main/_targets.R) condense down to [this one](https://wlandau.github.io/stantargets/articles/mcmc_rep.html) without loss of technical sophistication or computing power. The former requires users to think carefully about dynamic branching and file tracking, and the latter uses domain knowledge to abstract away these intimidating concepts.

I thought you might like to know because it instantiates a successful pattern that my colleagues and I are actively pursuing: develop one general-purpose pipeline tool first, and then build friendlier methodology-specific workflow frameworks on top of that. Other possibilities include [`stantargets`](https://github.com/wlandau/stantargets)-like packages for JAGS, Greta, Keras, Torch, Tidymodels, etc. For you, I see potential in a [`stantargets`](https://github.com/wlandau/stantargets)-like package tailored to `nlmixr`. I do not have the domain knowledge to develop it myself, but I would be happy to discuss ideas and review code if this direction appeals to you.

**Comment by mattfidler** [comment]
Covariates can be accessed in the model by `$all.covs`

``` r
library(nlmixr)
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    wcl <- 0
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl + WT * wcl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

ui <- nlmixr(one.compartment)
#> ℹ parameter labels from comments will be replaced by 'label()'

ui$all.covs
#> [1] "WT"
```

<sup>Created on 2021-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

It doesn't follow the standard camelCase naming convention and was added before that was standardized.

**Comment by billdenney** [comment]
@wlandau, I'm making some good progress!  I have a few questions that aren't readily apparent in the documentation or examples that I found.  At a glance, does the method I'm using below look right to you?  (I'm not asking for a detailed code review just an impression).  Specific questions are:

* Is the method I'm using with `substitute()` the right way to set the targets up with `tar_target_raw()`?
* Is returning a list from `tar_nlmixr()` made up of the targets to run the right way to create the DSL-specific tarchetype?
* I want to be sure that my `data_simple` and `object_simple` targets do not conflict with any other names.  I did that by creating them with the `name` for the final object, a space, and "data_simple" or "object_simple".  Adding the space seems like it's probably not supported, but it did work.  Is there a better way to create these intermediate objects where I can ensure that they will not conflict with other objects?
    * I'm wanting to do this because there will be times where potentially hundreds of models (i.e. calls to `tar_nlmixr()`) could be created in a single target set.  So, the potential for name conflicts seems like it is not theoretical.
* I want to give `...` arguments to `tar_nlmixr()` so that they can be passed to `nlmixr::nlmixr()` in the last step, but I don't see a way to do this.  Similarly, I also want to pass arguments to `tar_target_raw()`. I think for that, I'd like to give a `...` argument that is passed to `tar_target_raw()` and a `.nlmixr_args=list()` argument that would be passed to `nlmixr::nlmixr()`.  Is there a good way to use `...` and `...`-like arguments with `tar_target_raw()` and its commands?

My example code is below.  It can be pasted into a file named `_targets.R` and run if `nlmixr` is installed.

```r
library(targets)

tar_nlmixr <- function(name, object, data, est=NULL, ..., .target_args=list()) {
  if (is.null(est)) {
    stop("'est' must not be null")
  }
  name <- targets::tar_deparse_language(substitute(name))
  name_obj_simple <- paste(name, "object_simple", sep=" ")
  name_data_simple <- paste(name, "data_simple", sep=" ")
  ret <-
    list(
      targets::tar_target_raw(
        name=name_obj_simple,
        command=
          substitute(
            nlmixr_object_simplify(object=object),
            list(object=substitute(object))
          ),
        packages="nlmixr"
      ),
      targets::tar_target_raw(
        name=name_data_simple,
        command=
          substitute(
            nlmixr_data_simplify(object=object_simple, data=data),
            list(
              object_simple=as.name(name_obj_simple),
              data=substitute(data)
            )
          )
      ),
      targets::tar_target_raw(
        name=name,
        command=
          substitute(
            nlmixr::nlmixr(
              object=object_simple,
              data=data_simple,
              est=est
            ),
            list(
              object_simple=as.name(name_obj_simple),
              data_simple=as.name(name_data_simple),
              est=substitute(est)
            )
          ),
        packages="nlmixr"
      )
    )
  ret
}

nlmixr_object_simplify <- function(object) {
  # drop comments since they won't affect most outputs and typically change
  # between interactive (when srcref is available) to batch (when srcref is not
  # available) mode.
  attr(object, "srcref") <- NULL
  ret <- nlmixr::nlmixr(object)
  # TODO: ret$model.name is always "object"; it may be better to set it to
  # as.character(substitute(object)), but that didn't work with initial testing.
  # (Or, maybe it's better to have it just be "object" so that it is simpler.)
  ret
}

#' Standardize and simplify data for nlmixr estimation
#' 
#' @inheritParams nlmixr::nlmixr data
#' @param object an nlmixr_ui object (e.g. the output of running
#'   \code{nlmixr(object=model)}
#' @return The data with the nlmixr column lower case and on the left and the
#'   covariate columns on the right and alphabetically sorted.
#' @export
nlmixr_data_simplify <- function(data, object) {
  nlmixr_cols <-
    c(
      # RxODE columns
      c("id", "time", "amt", "rate", "dur", "evid", "cmt", "ss", "ii", "addl"),
      # nlmixr columns
      c("dv", "mdv")
    )
  # nlmixr pays attention to the columns in a case-insensitive way for the
  # standard columns.  Verify that the data has case-insensitive column names
  # for these columns (for example not "ADDL" and "addl").
  mask_nlmixr_cols <- tolower(names(data)) %in% nlmixr_cols
  nlmixr_names <- names(data)[mask_nlmixr_cols]
  mask_duplicated <- duplicated(tolower(nlmixr_names))
  if (any(mask_duplicated)) {
    stop(
      "The following column(s) are duplicated when lower case: ",
      paste0("'", nlmixr_names[mask_duplicated], "'", collapse=", ")
    )
  }
  cov_names <- object$all.covs
  missing_cov <- setdiff(cov_names, names(data))
  if (length(missing_cov) > 0) {
    stop(
      "The following covariate column(s) are missing from the data: ",
      paste0("'", missing_cov, "'", collapse=", ")
    )
  }
  # Simplifying the nlmixr_names column names to always be lower case ensures
  # that upper/lower case column name changes will not affect the need to rerun.
  # Also, standardizing the column name order to always be the same will prevent
  # the need to rerun, so cov_names is sorted.
  setNames(
    object=data[, c(nlmixr_names, sort(cov_names)), drop=FALSE],
    nm=c(tolower(nlmixr_names), sort(cov_names))
  )
}

pheno <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

list(
  tar_nlmixr(name=pheno_model, object=pheno, data=nlmixr::pheno_sd, est="saem")
)

# The result should be approximately equivalent to the below manual method
# list(
#   targets::tar_target(
#     name=object_simple,
#     command=nlmixr_object_simplify(object=pheno),
#     packages="nlmixr"
#   ),
#   targets::tar_target(
#     name=data_simple,
#     command=nlmixr_data_simplify(object=object_simple, data=nlmixr::pheno_sd)
#   ),
#   targets::tar_target(
#     name=pheno_model,
#     command=nlmixr::nlmixr(object=object_simple, data=data_simple, est="saem"),
#     packages="nlmixr"
#   )
# )
```

**Comment by mattfidler** [comment]
Hi @billdenney 

nlmixr doesn't really use the `...` very much.  In some estimation routines it moves everything to the `control` option.  

The biggest options that should be captured by nlmixr are:
- nlmixr model
- nlmixr data
- estimation method (`est`)
- estimation control options (`control`)
- estimation output options (`table`)

Anything else is not really needed from my perspective. 

On the other hand, the targets you use are similar to the targets that you need for `rxSolve` which has a lot of solving options and even uses the `...` in certain circumstances.

Matt

**Comment by billdenney** [comment]
@mattfidler, Thanks for those pointers.  For `tar_nlmixr()`, I'll just focus on the arguments you list.  I would guess that there will be a `tar_rxSolve()` in the future which will need more thought about `...`.

**Comment by billdenney** [comment]
The initial code is now committed with 100% test coverage.  I'm sure that there will be more questions coming, but the initial concept is now covered...
