### ISSUE TITLE
Use `rxode2::etTrans()` instead of `nlmixr_data_simplify()`

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixrtargets#13]
@mattfidler, In an initial test, `rxode2::etTrans()` drops the MDV column.  This could be important for `nlmixr2targets` in case the `MDV` column changes.  Mainly, I want to be sure that all columns are captured.  Since `etTrans()` is an `rxode2` function, might it miss any columns that are estimation-focused rather than integration-focused.

**Comment by mattfidler** [comment]
@billdenney You are right.  `MDV` is not used by `nlmixr2` or `rxode2`, it simply translates it to an `EVID` equivalent.

As I was thinking, there are a few things that may change though:

- IDs may change, they are saved as factor information in `etTrans()`
- Time varying covariates and non-time-varying covariates are separated (and handled differently).

Perhaps it is easier to simply use `nlmixr_data_simplify()`

**Comment by mattfidler** [comment]
(Mostly for the `ID` issue.  Also using `etTrans` directly has not been widely tested so there may be some edge cases that I am not anticipating).

**Comment by billdenney** [comment]
It sounds like long-term solution could be to have this in `rxode2::etTrans()`, but the today solution is to use `nlmixr_data_simplify()`.
