### ISSUE TITLE
Allow model piping within a multi-target

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixrtargets#19]
Allow automatic detection of being in the same target to allow the model to be found, chosen, and passed into a pipe.

**Comment by mattfidler** [comment]
This is what I was going to test for in the review.  Let me know when this is done so I can test it and look to see if it is working well.

**Comment by billdenney** [comment]
@mattfidler, I just merged the changes for this.  It should now work with model piping within a multiple-model fitting call.  It should also detect circular (or hanging) references to models that do not exist or cannot be created.

I added it to the vignette: https://nlmixr2.github.io/nlmixr2targets/articles/estimating.html#model-piping-for-multiple-models-estimated-with-one-dataset
