### ISSUE TITLE
illegal opcode on Mac

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixrtargets#2]
@mattfidler, When running the tests on Mac, there is an issue with "illegal opcode" that appears to occur within `nlmixr_fit0()`, but based on the stack trace, it's not clear to me exactly where the error originates.  Can you please take a look and give your opinion?

https://github.com/nlmixrdevelopment/nlmixrtargets/runs/3713941891?check_suite_focus=true#step:6:164

**Comment by mattfidler** [comment]
This comes from symengine.  If you compile symengine instead of using the
rstudio package manager, this works fine.

I have an example in RxODE github actions and nlmixr github actions.

**Comment by billdenney** [comment]
This appears to be resolved.
