### ISSUE TITLE
Does model.name no longer exist?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixrtargets#4]
@mattfidler , As I was moving nlmixrtargets to nlmixr2targets, I found that the test below is failing due to the fact that `model.name` no longer exists.  Was it removed with the switch to `nlmixr2`(`est`)?

And more generally, is there anything new coming from the environment that should be removed from a model to simplify it so that it does not trigger a rerun of a model unnecessarily?

https://github.com/nlmixr2/nlmixr2targets/blob/dbe2bcdd3eea825d489cb1e9af563a5c1816652d/tests/testthat/test-simplify.R#L27-L30

**Comment by mattfidler** [comment]
It was removed as an oversight

**Comment by mattfidler** [comment]
`$md5` is now available on `rxode2`
