### ISSUE TITLE
Cannot use `tar_nlmixr()` to refit an existing model with new data

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixrtargets#9]

**Comment by billdenney** [comment]
It appears that covariates are not correctly detected, so they do not get passed to the dataset simplification step.

**Comment by billdenney** [comment]
@mattfidler, The following line of code fails for estimated `nlmixr2` models (as opposed to `rxode2` objects or functions).

https://github.com/nlmixr2/nlmixr2targets/blob/81c53ea11f24cc8bc347420b5044e5e7bce51bc9/R/simplify.R#L92

I tried running `as.rxUi`, `assertRxUi`, and `rxode2::rxode`, but none of those converted the fit model to an rxUi object.  I feel like I'm forgetting a good way to ensure that I'm working with an rxUi object.  Can you please remind me of the function I'm forgetting (or let me know that the method doesn't exist and I should dive into the `$ui` part of the object)?

As a related question, should I be accessing the `$all.covs` accessor or `$allCovs`?

**Comment by mattfidler** [comment]
In theory `as.rxUi` and `assertRxUi` should all return `ui` objects.  `rxode2::rxode2` most likely would return something else.

However, for `nlmixr2` fits it can also be accessed by `fit$ui` and I believe that `as.rxUi` and `assertRxUi` should all be aliases for this way of accessing the `ui` object.

I believe that `allCovs` is preferred, and `all.covs` is an alias (so I guess not preferred). In general the `camelCase` is likely the actual function and the `dot.case` is an old alias.
